import Link from "next/link";
import "./globals.css";
import { Control } from "./Control";

export const metadata = {
  title: "Web tutorials",
  description: "Generated by yonga",
};

export default async function RootLayout({ children }) {
  // 서버쪽에서 동적으로 생성한 정적인 내용을 클라이언트로 전달했기 때문에 js파일이 남아있다.

  // const res = await fetch("http://localhost:9999/topics", {
  //   // 0초 동안만 캐시를 유지하겠다는 의미임. 즉 캐시를 사용하지 않겠다는 말임!
  //   next: { revalidate: 0 },
  // });

  // NEXT_PUBLIC_ 접두사가 없으면 server component에서만 사용할 수 있고,
  // client component에서는 사용할 수 없습니다.
  const res = await fetch(`${process.env.NEXT_PUBLIC_API_URL}topics`, {
    // 항상 최신 데이터를 가져오도록 캐시를 사용하지 않는 것을 지시하는 거임.
    cache: "no-cache",
  });
  const topics = await res.json();

  return (
    <html>
      <body>
        <h1>
          <Link href="/">WEB</Link>
        </h1>
        <ol>
          {topics.map((topic) => {
            return (
              <li key={topic.id}>
                <Link href={`/read/${topic.id}`}>{topic.title}</Link>
              </li>
            );
          })}
        </ol>
        {children}
        <Control />
      </body>
    </html>
  );
}
